"""The UPS sense: which battery, and what "could not read" is allowed to mean.

This sense exists because the `power` sense reads `/sys/class/power_supply/*` and
keeps only `type == "Battery"` - so a UPS, which the kernel reports as
`type == "UPS"`, was filtered out by design. A machine with a UPS was
indistinguishable from a desktop, and the one question a UPS exists to answer had
no answer anywhere in the app.

**The whole point of this file is the difference between two answers that look
alike.** "No UPS is connected" and "I could not find out" are opposite claims, and
on a UPS the second one is the dangerous one: an unreachable UPS is
indistinguishable from a dead one, which is exactly why NUT's own `DEADTIME`
treats silence as on-battery. So every unreadable path below must report UNKNOWN
with its reason named, and no test may accept a clean answer from a fixture that
could not be read.

The sysfs and upsc fixtures are REAL directories and REAL command output - the
shape of `type`, `online` and `MONITOR` is what the kernel and NUT actually
produce, not what a docstring says.
"""

from __future__ import annotations

import os
import sys

import pytest

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "usr/lib/shani-chronoa"))

from shani_chronoa.senses import discover_senses  # noqa: E402
from shani_chronoa.senses import ups as up  # noqa: E402


UPS_LINE = "MONITOR myups@localhost 1 monuser pw master\n"
NO_MONITOR = ("# BEGIN shani-settings MONITOR (generated by the install hook)\n"
              "# END shani-settings MONITOR\nMINSUPPLIES 1\n")


def _sysfs(root, *, online=1, present=1, status="OL", type_="UPS"):
    """A real sysfs-shaped directory for one power_supply entry."""
    entry = root / "ups0"
    entry.mkdir(parents=True, exist_ok=True)
    (entry / "type").write_text(type_ + "\n")
    (entry / "online").write_text(f"{online}\n")
    (entry / "present").write_text(f"{present}\n")
    if status is not None:
        (entry / "status").write_text(status + "\n")
    return root


@pytest.fixture
def sense():
    return discover_senses()["ups"]


def _answer(sense):
    out = sense.run({})
    return out.text if hasattr(out, "text") else str(out)


# --- the loader contract ---------------------------------------------------


def test_the_sense_is_discovered_under_its_own_name():
    """A module carrying SKILLS is silently dropped as a library module, and a
    sense nobody discovers is a sense that never answers."""
    assert "ups" in discover_senses()
    assert [s.name for s in up.SENSES] == ["ups"]


def test_the_name_is_legal_as_a_gsettings_key_fragment():
    """The consent key is derived from the name, and glib-compile-schemas
    discards the ENTIRE schema file on one underscore - so a snake_case sense
    name would silently undeclare every other key."""
    name = up.SENSES[0].name
    assert "_" not in name
    assert name.replace("-", "").isalnum()


def test_the_consent_key_matches_the_name():
    from shani_chronoa.config import _SENSE_CONSENT_KEYS
    assert _SENSE_CONSENT_KEYS["ups"] == "ups-sense-enabled"


def test_sensitivity_is_in_the_vocabulary():
    """`"machine"` is not in it, and the loader refuses the whole sense over it."""
    assert up.SENSES[0].sensitivity == "public"


# --- the two answers that must never be confused ---------------------------


def test_a_machine_with_no_ups_says_so_rather_than_reporting_a_fault(sense, tmp_path, monkeypatch):
    monkeypatch.setattr(up, "_GLOB", tmp_path / "power_supply/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    (tmp_path / "power_supply").mkdir()
    text = _answer(sense)
    assert "No UPS is connected" in text
    # ...and it is not dressed as a fault.
    assert "UNKNOWN" not in text


def test_an_unreadable_sysfs_is_unknown_not_no_ups(sense, tmp_path, monkeypatch):
    """The control for the test above: the glob resolving to nothing must not
    read as 'no UPS' when the directory could not be consulted at all."""
    monkeypatch.setattr(up, "_GLOB", tmp_path / "power_supply/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    # No power_supply directory at all, so the glob cannot resolve.
    text = _answer(sense)
    assert "UNKNOWN" in text
    assert "not established that there is no UPS" in text


def test_a_configured_ups_that_cannot_be_read_says_so_beside_the_sysfs_answer(
        sense, tmp_path, monkeypatch):
    """The half-blind case, and the one my first version got wrong.

    The kernel's driver answers, so the sense reports it - that is not a guess.
    What it must ALSO do is say NUT could not be read, because a reader who is
    told "on mains" and nothing else has no way to know the fuller picture
    (charge, runtime) was unavailable. Claiming the detail is fine would be the
    lie; omitting the failure would be the other one.
    """
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(NO_MONITOR + UPS_LINE)
    monkeypatch.setattr(up, "_resolve", lambda b: None)  # upsc not on PATH
    text = _answer(sense)
    assert "on mains" in text
    assert "NUT could not be read" in text
    # ...and it does not invent the numbers it could not read.
    assert "battery.charge" not in text


def test_nothing_can_answer_reports_unknown(sense, tmp_path, monkeypatch):
    """The other half, and the one that must be UNKNOWN: NUT is monitoring, so
    there IS a UPS, and neither sysfs nor upsc could answer. Reporting anything
    else would claim the power is fine when the truth is that nobody knows."""
    # A readable, EMPTY power_supply: "could not ask" is false, so the NUT
    # failure is the reason for UNKNOWN rather than the sysfs one.
    (tmp_path / "ps").mkdir()
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(NO_MONITOR + UPS_LINE)
    monkeypatch.setattr(up, "_resolve", lambda b: "/usr/bin/upsc")
    monkeypatch.setattr(up, "_read_upsc", lambda u, n: "upsc refused: Driver not connected")
    text = _answer(sense)
    assert "UNKNOWN" in text
    assert "unreachable UPS is not a healthy one" in text


# --- a UPS the kernel can see ---------------------------------------------


@pytest.mark.parametrize("online,expected", [
    (1, "on mains"),
    (0, "ON BATTERY"),
])
def test_sysfs_online_state_is_reported_and_not_inverted(sense, tmp_path, monkeypatch, online, expected):
    """`online` is what the driver knows about mains. Reading it backwards would
    report a machine on mains as running on battery and vice versa, and only one
    of those two mistakes is survivable."""
    _sysfs(tmp_path / "ps", online=online)
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    assert expected in _answer(sense)


def test_a_battery_entry_is_not_a_ups(sense, tmp_path, monkeypatch):
    """The whole reason this sense exists: `power` keeps `Battery`, this keeps
    `UPS`. A laptop's own pack must not be reported as an uninterruptible supply."""
    _sysfs(tmp_path / "ps", type_="Battery")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    assert "No UPS is connected" in _answer(sense)


def test_mains_is_not_a_ups(sense, tmp_path, monkeypatch):
    _sysfs(tmp_path / "ps", type_="Mains", status=None)
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    assert "No UPS is connected" in _answer(sense)


def test_on_battery_is_in_the_metadata(sense, tmp_path, monkeypatch):
    """The scheduler keys on this, so it is asserted rather than only implied by
    the sentence."""
    _sysfs(tmp_path / "ps", online=0)
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    out = sense.run({})
    assert (getattr(out, "metadata", None) or {}).get("on_battery") is True


# --- what is NOT read -----------------------------------------------------


def test_the_credential_file_is_never_read(sense, tmp_path, monkeypatch):
    """upsd.users holds the credential that can force a UPS power-down. Reading
    it into a percept would put it in an LLM prompt."""
    reads = []
    real_open = open

    def spy(path, *a, **k):
        if "upsd.users" in str(path):
            reads.append(str(path))
        return real_open(path, *a, **k)

    monkeypatch.setattr("builtins.open", spy)
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    _answer(sense)
    assert not reads, reads


def test_the_device_section_is_not_reported(sense, tmp_path, monkeypatch):
    """Which port and driver the hardware uses is not a fact worth sending to a
    model, and it is the part nut-scanner writes."""
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "no-such-upsmon.conf")
    text = _answer(sense)
    assert "upsd.users" not in text


# --- upsc parsing ---------------------------------------------------------


def test_upsc_values_containing_colons_survive_the_split():
    """`ups.mfr: American Power Conversion` has a colon in the value, and
    splitting on every colon keeps only its first field."""
    parsed = up._parse_upsc("ups.mfr: American Power Conversion\nbattery.charge: 100\n")
    assert parsed["ups.mfr"] == "American Power Conversion"
    assert parsed["battery.charge"] == "100"


def test_upsc_output_is_parsed_into_the_percept(sense, tmp_path, monkeypatch):
    _sysfs(tmp_path / "ps", online=0, status="OB DISCHRG")
    monkeypatch.setattr(up, "_resolve", lambda b: "/usr/bin/upsc")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(UPS_LINE)
    monkeypatch.setattr(up, "_read_upsc",
                        lambda u, n: "OK:ups.status: OB LB\nbattery.charge: 12\n"
                                    "battery.runtime: 300\nups.load: 25\n")
    text = _answer(sense)
    assert "ON BATTERY" in text
    assert "mains is out" in text
    assert "battery.charge: 12" in text
    assert "battery.runtime: 300" in text


def test_an_empty_but_successful_upsc_is_not_a_failure():
    """The "OK:" prefix makes an empty read distinguishable from an error, and a
    bare empty string would have been read as failure."""
    assert up._parse_upsc("") == {}


def test_the_monitor_name_is_what_upsc_is_asked_for(sense, tmp_path, monkeypatch):
    """The MONITOR line's system is `<name>@<host>` and upsc needs the bare name.
    Asking it for the whole string fails silently."""
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_resolve", lambda b: "/usr/bin/upsc")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(UPS_LINE)
    asked = []
    monkeypatch.setattr(up, "_read_upsc", lambda u, n: asked.append(n) or "OK:x: 1")
    _answer(sense)
    assert asked == ["myups"]


def test_a_refused_upsc_is_reported_not_swallowed(sense, tmp_path, monkeypatch):
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_resolve", lambda b: "/usr/bin/upsc")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(UPS_LINE)
    monkeypatch.setattr(up, "_read_upsc", lambda u, n: "upsc refused: Driver not connected")
    text = _answer(sense)
    assert "could not be read" in text
    assert "Driver not connected" in text


def test_a_commented_monitor_line_is_not_a_monitored_ups(sense, tmp_path, monkeypatch):
    """The shipped file's MONITOR line is commented out between markers, so a
    machine right after install has a policy and nothing to apply it to."""
    _sysfs(tmp_path / "ps")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(NO_MONITOR)
    assert up._monitor_name() is None
    # sysfs still answers, even with nothing monitored - that half needs no NUT.
    text = _answer(sense)
    assert "on mains" in text or "ON BATTERY" in text


# --- the consent gate -----------------------------------------------------


def test_consent_off_is_refused_by_name(sense):
    out = sense.run({})
    text = out.text if hasattr(out, "text") else str(out)
    if "turned off" not in text:
        pytest.skip("consent is granted here; the refusal path is covered by the "
                    "shared consent suite")
    assert "ups-sense-enabled" in text


def test_sysfs_and_upsc_disagreeing_is_said_not_resolved_silently(
        sense, tmp_path, monkeypatch):
    """The kernel's driver and NUT's daemon can disagree, and picking one without
    saying so is how a machine on mains comes to be reported as on battery.

    sysfs `online=1` with upsc `ups.status: OB` is exactly this. The sense reports
    the daemon's answer - it is the one actually talking to the hardware - but it
    names the disagreement, because a reader told only one of the two has no way
    to know the other was ever consulted.
    """
    _sysfs(tmp_path / "ps", online=1, status="OL")
    monkeypatch.setattr(up, "_GLOB", tmp_path / "ps/*")
    monkeypatch.setattr(up, "_UPSMON_CONF", tmp_path / "upsmon.conf")
    (tmp_path / "upsmon.conf").write_text(UPS_LINE)
    monkeypatch.setattr(up, "_resolve", lambda b: "/usr/bin/upsc")
    monkeypatch.setattr(up, "_read_upsc",
                        lambda u, n: "OK:ups.status: OB\nbattery.charge: 88\n")
    text = _answer(sense)
    assert "mains is out" in text          # the daemon's answer wins
    assert "disagree" in text              # ...and the disagreement is named
    assert "battery.charge: 88" in text
