"""`read_video`, `read_audio`, `read_image` and `edit_video`: four skills, no tests.

The whole media family had no test file mentioning it — each was green because
a hand-run demo passed once. These four share ffprobe/Pillow/ffmpeg, and this
box has all three, so every assertion below runs the **real binary against a
real file generated by ffmpeg itself** (`testsrc` for the video, `sine` for the
audio, Pillow for the picture).

That matters more here than elsewhere: all four parse machine output, and the
shapes below are read out of real output rather than remembered — the same
lesson as `pdffonts`' fixed-width table and `bootctl`'s three markers.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys

import pytest

_REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO / "usr" / "lib" / "shani-chronoa"))

from shani_chronoa.skills import edit_video as EV  # noqa: E402
from shani_chronoa.skills import read_audio as RA  # noqa: E402
from shani_chronoa.skills import read_image as RI  # noqa: E402
from shani_chronoa.skills import read_video as RV  # noqa: E402

_NEEDS = ("ffmpeg", "ffprobe")


def _needs_ffmpeg():
    return all(shutil.which(b) for b in _NEEDS)


@pytest.fixture
def home(tmp_path, monkeypatch):
    h = tmp_path / "home"
    h.mkdir(exist_ok=True)
    monkeypatch.setenv("HOME", str(h))
    return h


@pytest.fixture
def video(home):
    """A real 1-second 64x48 video, made by ffmpeg."""
    p = home / "tiny.mp4"
    subprocess.run(["ffmpeg", "-f", "lavfi", "-i", "testsrc=duration=1:size=64x48:rate=2",
                    "-y", str(p)], capture_output=True, timeout=120, check=False)
    assert p.exists() and p.stat().st_size > 0, "fixture: ffmpeg made no video"
    return p


@pytest.fixture
def audio(home):
    p = home / "tiny.m4a"
    subprocess.run(["ffmpeg", "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
                    "-y", str(p)], capture_output=True, timeout=120, check=False)
    assert p.exists() and p.stat().st_size > 0, "fixture: ffmpeg made no audio"
    return p


@pytest.fixture
def picture(home):
    p = home / "tiny.png"
    subprocess.run(["ffmpeg", "-f", "lavfi", "-i", "testsrc=duration=1:size=40x30:rate=1",
                    "-frames:v", "1", "-y", str(p)], capture_output=True, timeout=120, check=False)
    assert p.exists(), "fixture: ffmpeg made no picture"
    return p


# --- read_video ---------------------------------------------------------------

@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_real_video_reports_its_dimensions_and_duration(video):
    out = RV._run({"path": str(video)})
    assert "64" in out and "48" in out, out          # the real frame size
    assert "0:00:01" in out or "1" in out, out       # the real duration


@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_missing_video_is_not_a_video_with_no_details(monkeypatch, home):
    monkeypatch.setattr(RV.shutil, "which", lambda b: None)
    out = RV._run({"path": str(home / "nope.mp4")})
    assert "ffprobe" in out
    assert "not installed" in out


@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_file_that_is_not_a_video_is_refused_not_described(home):
    plain = home / "nota.txt"
    plain.write_text("this is text\n")
    out = RV._run({"path": str(plain)})
    assert "could not read" in out.lower() or "not" in out.lower(), out


# --- read_audio ---------------------------------------------------------------

@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_real_audio_file_reports_its_length_and_rate(audio):
    out = RA._run({"path": str(audio)})
    assert "440" in out or "Hz" in out or "1" in out, out    # the sine's frequency
    assert "44100" in out or "sample" in out.lower(), out    # a real sample rate


# --- read_image ---------------------------------------------------------------

def test_a_real_picture_reports_its_dimensions_and_format(picture):
    """Pillow is optional like ffmpeg; when it is present the answer is real."""
    if RI._Image is None:
        pytest.skip("Pillow is not installed here")
    out = RI._run({"path": str(picture)})
    assert "40" in out and "30" in out, out           # the real frame size
    assert "PNG" in out or "png" in out.lower(), out  # the real format


def test_a_picture_is_never_modified(picture):
    """The one property this skill's docstring promises about the file.
    """
    if RI._Image is None:
        pytest.skip("Pillow is not installed here")
    before = picture.read_bytes()
    RI._run({"path": str(picture)})
    assert picture.read_bytes() == before


def test_a_missing_pillow_is_a_missing_binary(monkeypatch, picture):
    monkeypatch.setattr(RI, "_Image", None)
    out = RI._run({"path": str(picture)})
    assert "Pillow" in out
    assert "not installed" in out


# --- edit_video ---------------------------------------------------------------

@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_speeding_up_a_video_changes_its_duration(video, home):
    """The effect has to be real: the output's duration is read back with
    ffprobe rather than trusted from ffmpeg's exit code.
    """
    out_path = home / "faster.mp4"
    out = EV._run({"path": str(video), "speed": 2.0, "output": str(out_path)})
    assert out_path.exists(), out
    # Read the result back: a 1-second file at 2x is about half a second.
    r = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                        "-of", "default=nw=1:nk=1", str(out_path)],
                       capture_output=True, text=True, timeout=60)
    duration = float(r.stdout.strip())
    assert 0.3 <= duration <= 0.75, f"2x speed of 1s should be ~0.5s, got {duration}"


@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_combining_of_incompatible_flags_is_refused(video, home):
    """An unsupported combination is refused rather than half-applied."""
    out = EV._run({"path": str(video), "speed": 99.0, "output": str(home / "x.mp4")})
    assert "Speed must be between" in out, out
    assert not (home / "x.mp4").exists()


@pytest.mark.skipif(not _needs_ffmpeg(), reason="ffmpeg/ffprobe are not installed")
def test_a_missing_ffmpeg_is_a_missing_binary(monkeypatch, video, home):
    monkeypatch.setattr(EV.shutil, "which", lambda b: None)
    out = EV._run({"path": str(video), "speed": 2.0, "output": str(home / "x.mp4")})
    assert "ffmpeg" in out
    assert "not installed" in out
    assert not (home / "x.mp4").exists()
